/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/apple": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign In With Apple */
    post: operations["sign_in_with_apple_v1_auth_apple_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/google": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign In With Google */
    post: operations["sign_in_with_google_v1_auth_google_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["logout_v1_auth_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh Session */
    post: operations["refresh_session_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Exercises Route */
    get: operations["list_exercises_route_v1_exercises_get"];
    put?: never;
    /** Create Exercise Route */
    post: operations["create_exercise_route_v1_exercises_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/exercises/{exercise_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Exercise Route */
    get: operations["get_exercise_route_v1_exercises__exercise_id__get"];
    put?: never;
    post?: never;
    /** Delete Exercise Route */
    delete: operations["delete_exercise_route_v1_exercises__exercise_id__delete"];
    options?: never;
    head?: never;
    /** Update Exercise Route */
    patch: operations["update_exercise_route_v1_exercises__exercise_id__patch"];
    trace?: never;
  };
  "/v1/exercises/{exercise_id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive Exercise Route */
    post: operations["archive_exercise_route_v1_exercises__exercise_id__archive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_v1_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Me */
    get: operations["read_me_v1_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations["update_me_v1_me_patch"];
    trace?: never;
  };
  "/v1/program-day-exercises/{pde_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Program Day Exercise */
    delete: operations["delete_program_day_exercise_v1_program_day_exercises__pde_id__delete"];
    options?: never;
    head?: never;
    /** Patch Program Day Exercise */
    patch: operations["patch_program_day_exercise_v1_program_day_exercises__pde_id__patch"];
    trace?: never;
  };
  "/v1/program-days/{day_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Program Day */
    delete: operations["delete_program_day_v1_program_days__day_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/program-days/{day_id}/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Program Day Exercise */
    post: operations["add_program_day_exercise_v1_program_days__day_id__exercises_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/program-templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Program Templates */
    get: operations["list_program_templates_v1_program_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/program-templates/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Program Template */
    get: operations["get_program_template_v1_program_templates__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/program-templates/{slug}/copy": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Copy Program Template */
    post: operations["copy_program_template_v1_program_templates__slug__copy_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/programs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Programs */
    get: operations["list_programs_v1_programs_get"];
    put?: never;
    /** Create Program */
    post: operations["create_program_v1_programs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/programs/{program_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Program */
    get: operations["get_program_v1_programs__program_id__get"];
    put?: never;
    post?: never;
    /** Delete Program */
    delete: operations["delete_program_v1_programs__program_id__delete"];
    options?: never;
    head?: never;
    /** Patch Program */
    patch: operations["patch_program_v1_programs__program_id__patch"];
    trace?: never;
  };
  "/v1/programs/{program_id}/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Program */
    post: operations["activate_program_v1_programs__program_id__activate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/programs/{program_id}/days": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Program Day */
    post: operations["create_program_day_v1_programs__program_id__days_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/programs/{program_id}/deactivate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Deactivate Program */
    post: operations["deactivate_program_v1_programs__program_id__deactivate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/scheduled-workouts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Scheduled Workouts */
    get: operations["list_scheduled_workouts_v1_scheduled_workouts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/scheduled-workouts/{scheduled_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Scheduled Workout */
    patch: operations["patch_scheduled_workout_v1_scheduled_workouts__scheduled_id__patch"];
    trace?: never;
  };
  "/v1/scheduled-workouts/{scheduled_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Scheduled Workout */
    post: operations["start_scheduled_workout_v1_scheduled_workouts__scheduled_id__start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/sets/{set_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Set */
    delete: operations["remove_set_v1_sets__set_id__delete"];
    options?: never;
    head?: never;
    /** Patch Set */
    patch: operations["patch_set_v1_sets__set_id__patch"];
    trace?: never;
  };
  "/v1/workout-exercises/{workout_exercise_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Workout Exercise */
    delete: operations["remove_workout_exercise_v1_workout_exercises__workout_exercise_id__delete"];
    options?: never;
    head?: never;
    /** Patch Workout Exercise */
    patch: operations["patch_workout_exercise_v1_workout_exercises__workout_exercise_id__patch"];
    trace?: never;
  };
  "/v1/workout-exercises/{workout_exercise_id}/reorder": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder Workout Exercise */
    post: operations["reorder_workout_exercise_v1_workout_exercises__workout_exercise_id__reorder_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workout-exercises/{workout_exercise_id}/sets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Workout Set */
    post: operations["add_workout_set_v1_workout_exercises__workout_exercise_id__sets_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workout-sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Workout Sessions */
    get: operations["list_workout_sessions_v1_workout_sessions_get"];
    put?: never;
    /** Create Workout Session */
    post: operations["create_workout_session_v1_workout_sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workout-sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Workout Session */
    get: operations["get_workout_session_v1_workout_sessions__session_id__get"];
    put?: never;
    post?: never;
    /** Delete Workout Session */
    delete: operations["delete_workout_session_v1_workout_sessions__session_id__delete"];
    options?: never;
    head?: never;
    /** Patch Workout Session */
    patch: operations["patch_workout_session_v1_workout_sessions__session_id__patch"];
    trace?: never;
  };
  "/v1/workout-sessions/{session_id}/exercises": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Workout Exercise */
    post: operations["add_workout_exercise_v1_workout_sessions__session_id__exercises_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workout-sessions/{session_id}/finish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Finish Workout Session */
    post: operations["finish_workout_session_v1_workout_sessions__session_id__finish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/workout-sessions/{session_id}/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Workout Session */
    post: operations["restore_workout_session_v1_workout_sessions__session_id__restore_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActivateRequest */
    ActivateRequest: {
      /**
       * Skip Existing
       * @default true
       */
      skip_existing: boolean;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * Weekday Offset
       * @description ISO weekday for day_index=0 (0=Monday..6=Sunday).
       */
      weekday_offset: number;
    };
    /** ActivateResponse */
    ActivateResponse: {
      program: components["schemas"]["ProgramResponse"];
      /** Scheduled Count */
      scheduled_count: number;
      /** Skipped Count */
      skipped_count: number;
    };
    /**
     * Equipment
     * @enum {string}
     */
    Equipment:
      | "barbell"
      | "dumbbell"
      | "cable"
      | "machine"
      | "bodyweight"
      | "banded"
      | "kettlebell"
      | "smith_machine"
      | "trap_bar"
      | "ez_bar"
      | "plate_loaded"
      | "cardio_machine"
      | "other";
    /** ExerciseCreate */
    ExerciseCreate: {
      /** Cues */
      cues?: string | null;
      equipment: components["schemas"]["Equipment"];
      /**
       * Is Unilateral
       * @default false
       */
      is_unilateral: boolean;
      movement_pattern: components["schemas"]["MovementPattern"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      primary_muscle: components["schemas"]["Muscle"];
      /** Secondary Muscles */
      secondary_muscles?: components["schemas"]["Muscle"][];
      tracking_type: components["schemas"]["TrackingType"];
    };
    /** ExerciseList */
    ExerciseList: {
      /** Items */
      items: components["schemas"]["ExerciseResponse"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** ExerciseResponse */
    ExerciseResponse: {
      /** Archived At */
      archived_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Cues */
      cues?: string | null;
      equipment: components["schemas"]["Equipment"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Is Unilateral
       * @default false
       */
      is_unilateral: boolean;
      movement_pattern: components["schemas"]["MovementPattern"];
      /** Name */
      name: string;
      /** Notes */
      notes?: string | null;
      /** Owner Id */
      owner_id: string | null;
      primary_muscle: components["schemas"]["Muscle"];
      /** Secondary Muscles */
      secondary_muscles?: components["schemas"]["Muscle"][];
      /** Slug */
      slug: string;
      tracking_type: components["schemas"]["TrackingType"];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ExerciseUpdate */
    ExerciseUpdate: {
      /** Cues */
      cues?: string | null;
      equipment?: components["schemas"]["Equipment"] | null;
      /** Is Unilateral */
      is_unilateral?: boolean | null;
      movement_pattern?: components["schemas"]["MovementPattern"] | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      primary_muscle?: components["schemas"]["Muscle"] | null;
      /** Secondary Muscles */
      secondary_muscles?: components["schemas"]["Muscle"][] | null;
      tracking_type?: components["schemas"]["TrackingType"] | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Db
       * @enum {string}
       */
      db: "ok" | "down";
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
      /** Version */
      version: string;
    };
    /** LogoutResponse */
    LogoutResponse: {
      /**
       * Status
       * @default ok
       */
      status: string;
    };
    /** MeResponse */
    MeResponse: {
      /** Birthdate */
      birthdate: string | null;
      /** Display Name */
      display_name: string | null;
      /** Email */
      email: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      sex_at_birth: components["schemas"]["SexAtBirth"] | null;
      /** Timezone */
      timezone: string;
      unit_system: components["schemas"]["UnitSystem"];
    };
    /** MeUpdate */
    MeUpdate: {
      /** Birthdate */
      birthdate?: string | null;
      /** Display Name */
      display_name?: string | null;
      sex_at_birth?: components["schemas"]["SexAtBirth"] | null;
      /** Timezone */
      timezone?: string | null;
      unit_system?: components["schemas"]["UnitSystem"] | null;
    };
    /**
     * MovementPattern
     * @enum {string}
     */
    MovementPattern:
      | "squat"
      | "hinge"
      | "horizontal_push"
      | "vertical_push"
      | "horizontal_pull"
      | "vertical_pull"
      | "lunge"
      | "carry"
      | "rotation"
      | "anti_rotation"
      | "isolation"
      | "cardio";
    /**
     * Muscle
     * @enum {string}
     */
    Muscle:
      | "chest"
      | "lats"
      | "traps"
      | "rhomboids"
      | "rear_delts"
      | "side_delts"
      | "front_delts"
      | "biceps"
      | "triceps"
      | "forearms"
      | "abs"
      | "obliques"
      | "lower_back"
      | "glutes"
      | "quads"
      | "hamstrings"
      | "adductors"
      | "abductors"
      | "calves";
    /** ProgramCreate */
    ProgramCreate: {
      /** Days Per Week */
      days_per_week: number;
      /** Description */
      description?: string | null;
      goal: components["schemas"]["ProgramGoal"];
      /** Name */
      name: string;
      /** Weeks */
      weeks: number;
    };
    /** ProgramDayCreate */
    ProgramDayCreate: {
      /** Name */
      name: string;
    };
    /** ProgramDayExerciseCreate */
    ProgramDayExerciseCreate: {
      /**
       * Exercise Id
       * Format: uuid
       */
      exercise_id: string;
      /** Notes */
      notes?: string | null;
      /** @default none */
      progression_strategy: components["schemas"]["ProgressionStrategy"];
      /** Rest Seconds */
      rest_seconds?: number | null;
      /** Target Reps High */
      target_reps_high?: number | null;
      /** Target Reps Low */
      target_reps_low?: number | null;
      /** Target Rir High */
      target_rir_high?: number | null;
      /** Target Rir Low */
      target_rir_low?: number | null;
      /** Target Rpe High */
      target_rpe_high?: number | string | null;
      /** Target Rpe Low */
      target_rpe_low?: number | string | null;
      /** Target Sets */
      target_sets: number;
    };
    /** ProgramDayExerciseResponse */
    ProgramDayExerciseResponse: {
      /**
       * Exercise Id
       * Format: uuid
       */
      exercise_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Notes */
      notes: string | null;
      /** Position */
      position: number;
      progression_strategy: components["schemas"]["ProgressionStrategy"];
      /** Rest Seconds */
      rest_seconds: number | null;
      /** Target Reps High */
      target_reps_high: number | null;
      /** Target Reps Low */
      target_reps_low: number | null;
      /** Target Rir High */
      target_rir_high: number | null;
      /** Target Rir Low */
      target_rir_low: number | null;
      /** Target Rpe High */
      target_rpe_high: string | null;
      /** Target Rpe Low */
      target_rpe_low: string | null;
      /** Target Sets */
      target_sets: number;
    };
    /** ProgramDayExerciseUpdate */
    ProgramDayExerciseUpdate: {
      /** Notes */
      notes?: string | null;
      /** Position */
      position?: number | null;
      progression_strategy?: components["schemas"]["ProgressionStrategy"] | null;
      /** Rest Seconds */
      rest_seconds?: number | null;
      /** Target Reps High */
      target_reps_high?: number | null;
      /** Target Reps Low */
      target_reps_low?: number | null;
      /** Target Rir High */
      target_rir_high?: number | null;
      /** Target Rir Low */
      target_rir_low?: number | null;
      /** Target Rpe High */
      target_rpe_high?: number | string | null;
      /** Target Rpe Low */
      target_rpe_low?: number | string | null;
      /** Target Sets */
      target_sets?: number | null;
    };
    /** ProgramDayResponse */
    ProgramDayResponse: {
      /** Day Index */
      day_index: number;
      /** Exercises */
      exercises: components["schemas"]["ProgramDayExerciseResponse"][];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
    };
    /**
     * ProgramGoal
     * @enum {string}
     */
    ProgramGoal: "hypertrophy" | "strength" | "powerbuilding" | "fat_loss" | "general" | "custom";
    /** ProgramList */
    ProgramList: {
      /** Items */
      items: components["schemas"]["ProgramListItem"][];
    };
    /** ProgramListItem */
    ProgramListItem: {
      /** Activated At */
      activated_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Days Per Week */
      days_per_week: number;
      goal: components["schemas"]["ProgramGoal"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      source: components["schemas"]["ProgramSource"];
      /** Weeks */
      weeks: number;
    };
    /** ProgramResponse */
    ProgramResponse: {
      /** Activated At */
      activated_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Days */
      days: components["schemas"]["ProgramDayResponse"][];
      /** Days Per Week */
      days_per_week: number;
      /** Description */
      description: string | null;
      goal: components["schemas"]["ProgramGoal"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      source: components["schemas"]["ProgramSource"];
      /** Template Id */
      template_id: string | null;
      /** Weeks */
      weeks: number;
    };
    /**
     * ProgramSource
     * @enum {string}
     */
    ProgramSource: "template" | "manual" | "copied";
    /** ProgramTemplateFull */
    ProgramTemplateFull: {
      /** Author */
      author: string | null;
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /** Days Per Week */
      days_per_week: number;
      /** Description */
      description: string | null;
      goal: components["schemas"]["ProgramGoal"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Weeks */
      weeks: number;
    };
    /** ProgramTemplateList */
    ProgramTemplateList: {
      /** Items */
      items: components["schemas"]["ProgramTemplateSummary"][];
    };
    /** ProgramTemplateSummary */
    ProgramTemplateSummary: {
      /** Author */
      author: string | null;
      /** Days Per Week */
      days_per_week: number;
      /** Description */
      description: string | null;
      goal: components["schemas"]["ProgramGoal"];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /** Weeks */
      weeks: number;
    };
    /** ProgramUpdate */
    ProgramUpdate: {
      /** Days Per Week */
      days_per_week?: number | null;
      /** Description */
      description?: string | null;
      goal?: components["schemas"]["ProgramGoal"] | null;
      /** Name */
      name?: string | null;
      /** Weeks */
      weeks?: number | null;
    };
    /**
     * ProgressionStrategy
     * @enum {string}
     */
    ProgressionStrategy: "linear" | "double_progression" | "rpe_based" | "none";
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** ScheduledWorkoutList */
    ScheduledWorkoutList: {
      /** Items */
      items: components["schemas"]["ScheduledWorkoutWithDay"][];
    };
    /**
     * ScheduledWorkoutStatus
     * @enum {string}
     */
    ScheduledWorkoutStatus: "planned" | "in_progress" | "completed" | "skipped";
    /** ScheduledWorkoutUpdate */
    ScheduledWorkoutUpdate: {
      /** Is Deload */
      is_deload?: boolean | null;
      /** Mesocycle Week */
      mesocycle_week?: number | null;
      /** Scheduled For */
      scheduled_for?: string | null;
      status?: components["schemas"]["ScheduledWorkoutStatus"] | null;
    };
    /**
     * ScheduledWorkoutWithDay
     * @description Calendar view: includes the program day name and exercise count.
     */
    ScheduledWorkoutWithDay: {
      /** Exercise Count */
      exercise_count: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Deload */
      is_deload: boolean;
      /** Mesocycle Week */
      mesocycle_week: number | null;
      /** Program Day Id */
      program_day_id: string | null;
      /** Program Day Name */
      program_day_name: string | null;
      /** Program Id */
      program_id: string | null;
      /** Program Name */
      program_name: string | null;
      /**
       * Scheduled For
       * Format: date
       */
      scheduled_for: string;
      status: components["schemas"]["ScheduledWorkoutStatus"];
    };
    /**
     * SetCreate
     * @description Fields are all optional at the Pydantic layer because validity depends
     *     on the parent exercise's `tracking_type`, which the route resolves before
     *     calling `validate_set_payload`.
     */
    SetCreate: {
      /** Distance Meters */
      distance_meters?: number | string | null;
      /** Duration Seconds */
      duration_seconds?: number | null;
      /** Notes */
      notes?: string | null;
      /** Reps */
      reps?: number | null;
      /** Rir */
      rir?: number | null;
      /** Rpe */
      rpe?: number | string | null;
      /** Set Index */
      set_index?: number | null;
      /** @default working */
      set_type: components["schemas"]["SetType"];
      /** Weight Kg */
      weight_kg?: number | string | null;
    };
    /** SetResponse */
    SetResponse: {
      /** Distance Meters */
      distance_meters: string | null;
      /** Duration Seconds */
      duration_seconds: number | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Pr */
      is_pr: boolean;
      /** Notes */
      notes: string | null;
      /** Reps */
      reps: number | null;
      /** Rir */
      rir: number | null;
      /** Rpe */
      rpe: string | null;
      /** Set Index */
      set_index: number;
      set_type: components["schemas"]["SetType"];
      /** Weight Kg */
      weight_kg: string | null;
    };
    /**
     * SetType
     * @enum {string}
     */
    SetType:
      | "working"
      | "warmup"
      | "drop"
      | "myo_rep"
      | "cluster"
      | "top_set"
      | "back_off"
      | "amrap";
    /** SetUpdate */
    SetUpdate: {
      /** Distance Meters */
      distance_meters?: number | string | null;
      /** Duration Seconds */
      duration_seconds?: number | null;
      /** Notes */
      notes?: string | null;
      /** Reps */
      reps?: number | null;
      /** Rir */
      rir?: number | null;
      /** Rpe */
      rpe?: number | string | null;
      set_type?: components["schemas"]["SetType"] | null;
      /** Weight Kg */
      weight_kg?: number | string | null;
    };
    /**
     * SexAtBirth
     * @enum {string}
     */
    SexAtBirth: "male" | "female" | "other";
    /** SignInRequest */
    SignInRequest: {
      /** Id Token */
      id_token: string;
    };
    /** TokenPair */
    TokenPair: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default Bearer
       */
      token_type: string;
    };
    /**
     * TrackingType
     * @enum {string}
     */
    TrackingType:
      | "weight_reps"
      | "weight_reps_distance"
      | "weight_time"
      | "bodyweight_reps"
      | "weighted_bodyweight"
      | "time_only"
      | "distance_time"
      | "distance_time_pace"
      | "cardio_machine";
    /**
     * UnitSystem
     * @enum {string}
     */
    UnitSystem: "metric" | "imperial";
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WorkoutExerciseCreate */
    WorkoutExerciseCreate: {
      /**
       * Exercise Id
       * Format: uuid
       */
      exercise_id: string;
      /** Notes */
      notes?: string | null;
      /** Position */
      position?: number | null;
    };
    /** WorkoutExerciseReorder */
    WorkoutExerciseReorder: {
      /** Position */
      position: number;
    };
    /** WorkoutExerciseResponse */
    WorkoutExerciseResponse: {
      /**
       * Exercise Id
       * Format: uuid
       */
      exercise_id: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Notes */
      notes: string | null;
      /** Position */
      position: number;
      /** Sets */
      sets: components["schemas"]["SetResponse"][];
    };
    /** WorkoutExerciseUpdate */
    WorkoutExerciseUpdate: {
      /** Notes */
      notes?: string | null;
      /** Position */
      position?: number | null;
    };
    /** WorkoutSessionCreate */
    WorkoutSessionCreate: {
      /** Name */
      name?: string | null;
      /** Scheduled Workout Id */
      scheduled_workout_id?: string | null;
      /** Started At */
      started_at?: string | null;
    };
    /** WorkoutSessionList */
    WorkoutSessionList: {
      /** Items */
      items: components["schemas"]["WorkoutSessionListItem"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** WorkoutSessionListItem */
    WorkoutSessionListItem: {
      /** Bodyweight Kg */
      bodyweight_kg: string | null;
      /** Ended At */
      ended_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string | null;
      /** Perceived Exertion */
      perceived_exertion: number | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
    };
    /** WorkoutSessionResponse */
    WorkoutSessionResponse: {
      /** Bodyweight Kg */
      bodyweight_kg: string | null;
      /** Ended At */
      ended_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string | null;
      /** Notes */
      notes: string | null;
      /** Perceived Exertion */
      perceived_exertion: number | null;
      /** Scheduled Workout Id */
      scheduled_workout_id: string | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Workout Exercises */
      workout_exercises: components["schemas"]["WorkoutExerciseResponse"][];
    };
    /** WorkoutSessionUpdate */
    WorkoutSessionUpdate: {
      /** Bodyweight Kg */
      bodyweight_kg?: number | string | null;
      /** Ended At */
      ended_at?: string | null;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Perceived Exertion */
      perceived_exertion?: number | null;
      /** Started At */
      started_at?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  sign_in_with_apple_v1_auth_apple_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sign_in_with_google_v1_auth_google_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
    };
  };
  refresh_session_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_exercises_route_v1_exercises_get: {
    parameters: {
      query?: {
        q?: string | null;
        muscle?: components["schemas"]["Muscle"] | null;
        equipment?: components["schemas"]["Equipment"] | null;
        movement_pattern?: components["schemas"]["MovementPattern"] | null;
        tracking_type?: components["schemas"]["TrackingType"] | null;
        mine_only?: boolean;
        include_archived?: boolean;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExerciseList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_exercise_route_v1_exercises_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExerciseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_exercise_route_v1_exercises__exercise_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_exercise_route_v1_exercises__exercise_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_exercise_route_v1_exercises__exercise_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExerciseUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_exercise_route_v1_exercises__exercise_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        exercise_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  read_me_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
    };
  };
  update_me_v1_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MeUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_program_day_exercise_v1_program_day_exercises__pde_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pde_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_program_day_exercise_v1_program_day_exercises__pde_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        pde_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramDayExerciseUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_program_day_v1_program_days__day_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        day_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_program_day_exercise_v1_program_days__day_id__exercises_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        day_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramDayExerciseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_program_templates_v1_program_templates_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramTemplateList"];
        };
      };
    };
  };
  get_program_template_v1_program_templates__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramTemplateFull"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  copy_program_template_v1_program_templates__slug__copy_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_programs_v1_programs_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramList"];
        };
      };
    };
  };
  create_program_v1_programs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_program_v1_programs__program_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_program_v1_programs__program_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_program_v1_programs__program_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  activate_program_v1_programs__program_id__activate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ActivateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActivateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_program_day_v1_programs__program_id__days_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProgramDayCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramDayResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  deactivate_program_v1_programs__program_id__deactivate_post: {
    parameters: {
      query?: {
        skip_existing?: boolean;
      };
      header?: never;
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_scheduled_workouts_v1_scheduled_workouts_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScheduledWorkoutList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_scheduled_workout_v1_scheduled_workouts__scheduled_id__patch: {
    parameters: {
      query?: {
        shift_remaining_days?: number;
      };
      header?: never;
      path: {
        scheduled_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScheduledWorkoutUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScheduledWorkoutWithDay"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_scheduled_workout_v1_scheduled_workouts__scheduled_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scheduled_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_set_v1_sets__set_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        set_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_set_v1_sets__set_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        set_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_workout_exercise_v1_workout_exercises__workout_exercise_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_exercise_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_workout_exercise_v1_workout_exercises__workout_exercise_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_exercise_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkoutExerciseUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reorder_workout_exercise_v1_workout_exercises__workout_exercise_id__reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workout_exercise_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkoutExerciseReorder"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_workout_set_v1_workout_exercises__workout_exercise_id__sets_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path: {
        workout_exercise_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SetResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_workout_sessions_v1_workout_sessions_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionList"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_workout_session_v1_workout_sessions_post: {
    parameters: {
      query?: never;
      header?: {
        "Idempotency-Key"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkoutSessionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_workout_session_v1_workout_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_workout_session_v1_workout_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_workout_session_v1_workout_sessions__session_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkoutSessionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_workout_exercise_v1_workout_sessions__session_id__exercises_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WorkoutExerciseCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutExerciseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  finish_workout_session_v1_workout_sessions__session_id__finish_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  restore_workout_session_v1_workout_sessions__session_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WorkoutSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
