from seed.programs._dsl import day, exercise, program

SLUGS = {
    "bench": "barbell-bench-press-medium-grip",
    "incline_bench": "barbell-incline-bench-press-medium-grip",
    "dumbbell_fly": "dumbbell-flyes",
    "pull_up": "pullups",
    "barbell_row": "bent-over-barbell-row",
    "one_arm_row": "one-arm-dumbbell-row",
    "lat_pulldown": "wide-grip-lat-pulldown",
    "barbell_curl": "barbell-curl",
    "hammer_curl": "alternate-hammer-curl",
    "ohp": "barbell-shoulder-press",
    "arnold_press": "arnold-dumbbell-press",
    "lateral_raise": "side-lateral-raise",
    "rear_delt_fly": "reverse-flyes",
    "barbell_shrug": "barbell-shrug",
    "close_grip_bench": "close-grip-barbell-bench-press",
    "triceps_pushdown": "triceps-pushdown",
    "overhead_triceps_ext": "cable-rope-overhead-triceps-extension",
    "squat": "barbell-squat",
    "rdl": "romanian-deadlift",
    "leg_press": "leg-press",
    "leg_curl": "lying-leg-curls",
    "leg_extension": "leg-extensions",
    "standing_calf": "standing-calf-raises",
    "seated_calf": "seated-calf-raise",
    "cable_crunch": "cable-crunch",
}

template = program(
    slug="arnold-split-6day",
    name="Arnold Split (6-day)",
    description="Chest+Back / Shoulders+Arms / Legs, twice through the week. High volume, Golden Era style.",
    author="Curated",
    goal="hypertrophy",
    weeks=6,
    days_per_week=6,
    slug_map=SLUGS,
    days=[
        day(
            "Chest + Back A",
            exercises=[
                exercise(
                    "bench",
                    sets=4,
                    reps=(6, 10),
                    rpe=(7, 8),
                    rest=150,
                    progression="double_progression",
                ),
                exercise("incline_bench", sets=3, reps=(8, 12), rpe=(7, 9), rest=120),
                exercise("dumbbell_fly", sets=3, reps=(10, 15), rpe=(8, 9), rest=75),
                exercise(
                    "pull_up",
                    sets=4,
                    reps=(5, 10),
                    rpe=(7, 9),
                    rest=120,
                    progression="double_progression",
                ),
                exercise("barbell_row", sets=3, reps=(8, 12), rpe=(7, 9), rest=120),
                exercise("one_arm_row", sets=3, reps=(10, 15), rpe=(8, 9), rest=75),
            ],
        ),
        day(
            "Shoulders + Arms A",
            exercises=[
                exercise(
                    "ohp",
                    sets=4,
                    reps=(6, 10),
                    rpe=(7, 8),
                    rest=150,
                    progression="double_progression",
                ),
                exercise("arnold_press", sets=3, reps=(8, 12), rpe=(7, 9), rest=90),
                exercise("lateral_raise", sets=4, reps=(12, 20), rpe=(8, 10), rest=60),
                exercise("rear_delt_fly", sets=3, reps=(12, 20), rpe=(8, 10), rest=60),
                exercise("barbell_curl", sets=4, reps=(8, 12), rpe=(8, 9), rest=75),
                exercise("close_grip_bench", sets=4, reps=(6, 10), rpe=(7, 8), rest=120),
            ],
        ),
        day(
            "Legs A",
            exercises=[
                exercise("squat", sets=4, reps=(6, 10), rpe=(7, 8), rest=240, progression="linear"),
                exercise("rdl", sets=3, reps=(8, 12), rpe=(7, 8), rest=150),
                exercise("leg_press", sets=3, reps=(12, 20), rpe=(8, 9), rest=120),
                exercise("leg_curl", sets=3, reps=(10, 15), rpe=(8, 9), rest=75),
                exercise("standing_calf", sets=5, reps=(10, 15), rpe=(8, 10), rest=60),
            ],
        ),
        day(
            "Chest + Back B",
            exercises=[
                exercise(
                    "incline_bench",
                    sets=4,
                    reps=(6, 10),
                    rpe=(7, 8),
                    rest=150,
                    progression="double_progression",
                ),
                exercise("bench", sets=3, reps=(8, 12), rpe=(7, 9), rest=120),
                exercise("dumbbell_fly", sets=3, reps=(12, 15), rpe=(8, 10), rest=60),
                exercise("lat_pulldown", sets=4, reps=(10, 15), rpe=(8, 9), rest=90),
                exercise("barbell_row", sets=3, reps=(8, 12), rpe=(7, 9), rest=120),
                exercise("barbell_shrug", sets=3, reps=(10, 15), rpe=(8, 10), rest=75),
            ],
        ),
        day(
            "Shoulders + Arms B",
            exercises=[
                exercise(
                    "arnold_press",
                    sets=4,
                    reps=(8, 12),
                    rpe=(7, 9),
                    rest=120,
                    progression="double_progression",
                ),
                exercise("lateral_raise", sets=4, reps=(15, 25), rpe=(8, 10), rest=45),
                exercise("rear_delt_fly", sets=3, reps=(15, 25), rpe=(8, 10), rest=45),
                exercise("hammer_curl", sets=4, reps=(10, 15), rpe=(8, 9), rest=60),
                exercise("triceps_pushdown", sets=4, reps=(10, 15), rpe=(8, 9), rest=60),
                exercise("overhead_triceps_ext", sets=3, reps=(10, 15), rpe=(8, 9), rest=75),
            ],
        ),
        day(
            "Legs B",
            exercises=[
                exercise("rdl", sets=4, reps=(5, 8), rpe=(7, 8), rest=180, progression="linear"),
                exercise("squat", sets=3, reps=(8, 12), rpe=(7, 8), rest=180),
                exercise("leg_extension", sets=4, reps=(12, 20), rpe=(8, 10), rest=60),
                exercise("leg_curl", sets=4, reps=(12, 15), rpe=(8, 10), rest=60),
                exercise("seated_calf", sets=5, reps=(12, 20), rpe=(8, 10), rest=45),
                exercise("cable_crunch", sets=3, reps=(15, 25), rpe=(8, 10), rest=60),
            ],
        ),
    ],
)
